// Package exporter provides functionality to export comparison results
// to various file formats such as .env templates or markdown reports.
package exporter

import (
	"fmt"
	"os"
	"strings"

	"github.com/user/envdiff/internal/comparator"
)

// Format represents the export file format.
type Format string

const (
	// FormatEnvTemplate exports a .env template with missing keys as empty placeholders.
	FormatEnvTemplate Format = "env-template"
	// FormatMarkdown exports a markdown table summarising the diff results.
	FormatMarkdown Format = "markdown"
)

// Export writes the comparison results to the given file path in the specified format.
func Export(results []comparator.Result, format Format, outputPath string) error {
	var content string
	var err error

	switch format {
	case FormatEnvTemplate:
		content, err = renderEnvTemplate(results)
	case FormatMarkdown:
		content, err = renderMarkdown(results)
	default:
		return fmt.Errorf("unsupported export format: %q", format)
	}

	if err != nil {
		return fmt.Errorf("rendering export: %w", err)
	}

	if err := os.WriteFile(outputPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing export file: %w", err)
	}

	return nil
}

// renderEnvTemplate produces a .env-style template where missing keys are
// listed with empty values and mismatched keys include a comment.
func renderEnvTemplate(results []comparator.Result) (string, error) {
	var sb strings.Builder
	sb.WriteString("# Generated by envdiff — fill in missing or mismatched values\n\n")

	for _, r := range results {
		switch r.Status {
		case comparator.StatusMissing:
			fmt.Fprintf(&sb, "# MISSING in %s\n%s=\n\n", strings.Join(r.MissingIn, ", "), r.Key)
		case comparator.StatusMismatch:
			fmt.Fprintf(&sb, "# MISMATCH: %s\n%s=\n\n", r.Key, r.Key)
		}
	}

	return sb.String(), nil
}

// renderMarkdown produces a markdown table of all diff results.
func renderMarkdown(results []comparator.Result) (string, error) {
	var sb strings.Builder
	sb.WriteString("# envdiff Report\n\n")
	sb.WriteString("| Key | Status | Detail |\n")
	sb.WriteString("|-----|--------|--------|\n")

	for _, r := range results {
		var detail string
		switch r.Status {
		case comparator.StatusMissing:
			detail = fmt.Sprintf("Missing in: %s", strings.Join(r.MissingIn, ", "))
		case comparator.StatusMismatch:
			detail = "Values differ across environments"
		default:
			detail = "OK"
		}
		fmt.Fprintf(&sb, "| %s | %s | %s |\n", r.Key, r.Status, detail)
	}

	return sb.String(), nil
}
